### ISSUE TITLE
IE always thinks HTTPS URLs aren't relative

### ISSUE THREAD

**Issue by dlockhart** [BrightspaceUI/ajax#17]
The problem is in [_isRelativeUrl](https://github.com/BrightspaceUI/ajax/blob/master/d2l-ajax.html#L200):

```
_isRelativeUrl: function (url) {
	// In IE, relative paths have no host or protocol
	return !url.host
		|| !url.protocol
		|| (url.host === location.host
			&& url.protocol === location.protocol);
}
```

In IE, when SSL is enabled, for some reason it includes the port in `host`, so `url.host` -> `myhostname.com:443`. When that's compared to `location.host`, it fails.

@ryantmer just an FYI, I'll be fixing this today

**Comment by ryantmer** [comment]
Oof, that's a fun one. Thanks for looking into this!
